
package nic.vahan.web.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VahanInfo", targetNamespace = "http://server.web.vahan.nic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VahanInfo {


    /**
     * 
     * @param clientId
     * @param regnNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDetails", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetDetails")
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetDetailsResponse")
    @Action(input = "http://server.web.vahan.nic/VahanInfo/getDetailsRequest", output = "http://server.web.vahan.nic/VahanInfo/getDetailsResponse")
    public String getDetails(
        @WebParam(name = "client_id", targetNamespace = "")
        String clientId,
        @WebParam(name = "regn_no", targetNamespace = "")
        String regnNo);

    /**
     * 
     * @param clientId
     * @param chasiNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChasisDetails", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetChasisDetails")
    @ResponseWrapper(localName = "getChasisDetailsResponse", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetChasisDetailsResponse")
    @Action(input = "http://server.web.vahan.nic/VahanInfo/getChasisDetailsRequest", output = "http://server.web.vahan.nic/VahanInfo/getChasisDetailsResponse")
    public String getChasisDetails(
        @WebParam(name = "client_id", targetNamespace = "")
        String clientId,
        @WebParam(name = "chasi_no", targetNamespace = "")
        String chasiNo);

    /**
     * 
     * @param engineNo
     * @param clientId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEngineDetails", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetEngineDetails")
    @ResponseWrapper(localName = "getEngineDetailsResponse", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.GetEngineDetailsResponse")
    @Action(input = "http://server.web.vahan.nic/VahanInfo/getEngineDetailsRequest", output = "http://server.web.vahan.nic/VahanInfo/getEngineDetailsResponse")
    public String getEngineDetails(
        @WebParam(name = "client_id", targetNamespace = "")
        String clientId,
        @WebParam(name = "engine_no", targetNamespace = "")
        String engineNo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parseCurrentDateToString", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.ParseCurrentDateToString")
    @ResponseWrapper(localName = "parseCurrentDateToStringResponse", targetNamespace = "http://server.web.vahan.nic/", className = "nic.vahan.web.server.ParseCurrentDateToStringResponse")
    @Action(input = "http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringRequest", output = "http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringResponse")
    public String parseCurrentDateToString();

}
